"""Add the mtime column for file change detection

Revision ID: 234b6fa583f1
Revises: ceb0475b998c
Create Date: 2026-09-13 17:10:51.288398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234b6fa583f1'
down_revision: Union[str, Sequence[str], None] = 'ceb0475b998c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('file_mtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'file_mtime')
    # ### end Alembic commands ###
