"""Add device_name and ip_address tracking

Revision ID: 26b4189fad10
Revises: 86d89f474879
Create Date: 2026-09-20 13:58:31.093195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b4189fad10'
down_revision: Union[str, Sequence[str], None] = '86d89f474879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('device_name', sa.String(length=255), nullable=True))
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'user_agent')
    op.drop_column('refresh_tokens', 'device_name')
    # ### end Alembic commands ###
