"""Add JTI Column to Refresh cache table

Revision ID: 38b998f89bb2
Revises: 896b4c9ea330
Create Date: 2026-07-05 11:47:39.567982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b998f89bb2'
down_revision: Union[str, Sequence[str], None] = '896b4c9ea330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('jti', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'jti')
    # ### end Alembic commands ###
