"""Add Valid till timestamp for refresh token

Revision ID: 3d54e2e917ad
Revises: 546440ad0daf
Create Date: 2026-06-14 17:52:14.268486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d54e2e917ad'
down_revision: Union[str, Sequence[str], None] = '546440ad0daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
