"""Add Valid till timestamp for refresh token

Revision ID: 546440ad0daf
Revises: 83c6c0e93b90
Create Date: 2026-06-14 17:51:04.563542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546440ad0daf'
down_revision: Union[str, Sequence[str], None] = '83c6c0e93b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('valid_till', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'refresh_tokens', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_column('refresh_tokens', 'valid_till')
    # ### end Alembic commands ###
