"""Drop Unique from refresh table

Revision ID: 83c6c0e93b90
Revises: ee24ff43a825
Create Date: 2026-06-14 16:56:04.976147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c6c0e93b90'
down_revision: Union[str, Sequence[str], None] = 'ee24ff43a825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_tokens_refresh_token_key'), 'refresh_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('refresh_tokens_refresh_token_key'), 'refresh_tokens', ['refresh_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
