"""Add unique for user_id in playback state

Revision ID: 86d89f474879
Revises: ad5018d5d6b5
Create Date: 2026-09-19 15:17:01.823514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d89f474879'
down_revision: Union[str, Sequence[str], None] = 'ad5018d5d6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'playback_state', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playback_state', type_='unique')
    # ### end Alembic commands ###
