"""Drop unique for user id

Revision ID: 896b4c9ea330
Revises: 3d54e2e917ad
Create Date: 2026-06-14 18:58:17.517354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896b4c9ea330'
down_revision: Union[str, Sequence[str], None] = '3d54e2e917ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_tokens_user_id_key'), 'refresh_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('refresh_tokens_user_id_key'), 'refresh_tokens', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
