"""Add track id to playback state

Revision ID: ad5018d5d6b5
Revises: 673f6b71224a
Create Date: 2026-09-18 23:15:05.534815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5018d5d6b5'
down_revision: Union[str, Sequence[str], None] = '673f6b71224a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playback_state', sa.Column('track_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playback_state', 'track_id')
    # ### end Alembic commands ###
