"""Add the cover image path column

Revision ID: ceb0475b998c
Revises: bdad0ad6cd15
Create Date: 2026-09-13 16:33:01.419586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb0475b998c'
down_revision: Union[str, Sequence[str], None] = 'bdad0ad6cd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('cover_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'cover_path')
    # ### end Alembic commands ###
