"""add access jti to refresh tokens

Revision ID: cebe2cd71040
Revises: 26b4189fad10
Create Date: 2026-09-22 08:46:35.151111

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cebe2cd71040"
down_revision: Union[str, Sequence[str], None] = "26b4189fad10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "access_jti",
            sa.Uuid(),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "access_jti")
    # ### end Alembic commands ###
