"""
Revision ID: f45258b44048
Revises: 38b998f89bb2
Create Date: 2026-09-06 18:47:42.589714

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f45258b44048"
down_revision: Union[str, Sequence[str], None] = "38b998f89bb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    provider_type = sa.Enum(
        "GOOGLE",
        "NORMAL",
        name="providertype",
    )

    provider_type.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "users",
        sa.Column(
            "provider_type",
            provider_type,
            nullable=False,
            server_default="NORMAL",
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "first_name",
            sa.String(length=255),
            nullable=False,
            server_default="",
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "last_name",
            sa.String(length=255),
            nullable=False,
            server_default="",
        ),
    )

    op.drop_column("users", "name")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "users",
        sa.Column(
            "name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            server_default="",
        ),
    )

    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "provider_type")

    provider_type = sa.Enum(
        "GOOGLE",
        "NORMAL",
        name="providertype",
    )

    provider_type.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
